# Project information
site_name: Openterface | Conectăm Interfețele la Posibilități Deschise
site_url: https://ro.openterface.com/
site_author: Billy Wang
site_description: O soluție KVM-over-USB bogată în funcții, open-source și susținută de comunitate

# Repository
repo_name: Openterface
repo_url: https://github.com/TechxArtisanStudio/Openterface

# Copyright
copyright: >-
  Drepturi de autor &copy; Toate drepturile rezervate. 2023 <a href="https://www.openterface.com">Openterface</a> | <a href="https://www.techxartisan.com">TechxArtisan</a> | Guangzhou Billio Tech. Co., Ltd. <br>
  <a href="">Acasă</a> |
  <a href="/terms-of-service">Termeni și condiții</a> |
  <a href="/privacy-policy">Politica de confidențialitate</a> | 
  <a href="#__consent">Setări cookie-uri</a> | 
  <a href="/contact">Contactați-ne</a>


extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/signup_form.css

extra_javascript:
  - assets/javascripts/extra.js

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  language: ro
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/app-logo.png
  favicon: images/favicon.png
  features:
   - navigation.tabs
   - navigation.sections
   - navigation.top
   - navigation.footer
   - navigation.indexes
   - toc.integrate
   - search.suggest
   - search.highlight
   - content.tabs
   - content.code.annotation
   - content.code.copy
   - content.tabs.link

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

extra:
  social:
    - icon: txa/crowd-supply-icon
      link: https://www.crowdsupply.com/techxartisan/openterface-mini-kvm
    - icon: fontawesome/brands/reddit-alien
      link: /reddit
    - icon: fontawesome/brands/discord
      link: /discord
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@TechxArtisan
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/TechxArtisan
    - icon: fontawesome/brands/facebook-f
      link: https://www.facebook.com/TechxArtisan
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/techxartisan/
  
  alternate:
    - name: English
      link: https://openterface.com/
      lang: en
    - name: 简体中文
      lang: zh
      link: https://cn.openterface.com/
    - name: 日本語
      lang: ja
      link: https://jp.openterface.com/
    - name: 한국어
      lang: ko
      link: https://kr.openterface.com/
    - name: Français
      link: https://fr.openterface.com/
      lang: fr
    - name: Deutsch
      link: https://de.openterface.com/
      lang: de
    - name: Italiano
      link: https://it.openterface.com/
      lang: it
    - name: Español
      link: https://es.openterface.com/
      lang: es
    - name: Português
      link: https://pt.openterface.com/
      lang: pt
    - name: Română
      link: https://ro.openterface.com/
      lang: ro
    # - name: Svenska
    #   link: https://sv.openterface.com/
    #   lang: sv
    # - name: Polski
    #   link: https://pl.openterface.com/
    #   lang: pl
    # - name: Nederlands
    #   link: https://nl.openterface.com/
    #   lang: nl


  consent:
    title: Consimțământ pentru Cookie-uri
    description: >- 
      Folosim cookie-uri pentru a îmbunătăți calitatea conținutului documentației și pentru a analiza eficiența și nevoile site-ului. 
      Prin consimțământul tău, ne ajuți să îmbunătățim site-ul nostru. Mulțumim!
    actions:
      - accept
      - reject
  analytics:
    provider: google
    property: G-EKZEH6QYWT

markdown_extensions:
  # Enables tables
  - tables
  # Enables admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  # Enables emoji shortcodes like :+1: or :sunglasses:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
              custom_icons:
                - overrides/.icons
  - toc:
      permalink: ¶
      toc_depth: 3

plugins:
  - glightbox
  - search
  - redirects:
      redirect_maps:
        'basic-testing.md': 'basic.md'
        'community.md': 'https://www.reddit.com/r/Openterface_miniKVM/'
        'discord.md': 'https://discord.gg/sFTJD6a3R8'
        'reddit.md': 'https://www.reddit.com/r/Openterface_miniKVM/'
        'macos.md': 'https://github.com/TechxArtisanStudio/Openterface_MacOS'
        'android.md': 'https://github.com/TechxArtisanStudio/Openterface_Android'
        'qt.md': 'https://github.com/TechxArtisanStudio/Openterface_QT'
        'window.md': 'https://github.com/TechxArtisanStudio/Openterface_QT'
        'linux.md': 'https://github.com/TechxArtisanStudio/Openterface_QT'
        'hardware.md': 'https://github.com/TechxArtisanStudio/Openterface_Mini-KVM_Hardware'
        'feedback.md': 'https://forms.gle/YJLrCKwro8tbi6ar7'
        'oshw.md': 'https://certification.oshwa.org/cn000015.html'
        'x.md': 'https://x.com/TechxArtisan'
  - tags:
      tags_file: tags.md
  - blog:
      post_url_format: "{slug}"
      authors_file: "{blog}/.authors.yml"
      blog_toc: true
      post_excerpt_separator: <!-- more -->
      categories_name: Categories
      categories_toc: true
      pagination: true
      pagination_per_page: 10
      draft: true
      archive: false

nav:
  - Acasă: index.md
  - Documentație:
    - Ghid Rapid: quick-start.md
    - Funcționalități: features.md
    - Cum să Conectezi: how-to-connect.md
    - Software Deschis: app.md
    - Hardware Deschis: open-hardware.md
    - Control de Bază: basic.md
    - Port USB Comutabil: usb-switch.md
    - Pini de Extensie: pin.md
    - Cazuri de Utilizare: use-cases.md
    - Specificații: specifications.md
    - Ce Găsești în Cutie: whats-in-the-box.md
    - Accesorii: accessories.md
    - Cum Funcționează: how-it-works.md
    - De ce Openterface: why-openterface.md
    - Comparație: comparison.md
    - Întrebări Frecvente: faq.md
    - Dezvoltare:
      - Testare și Dezvoltare: test.md
      - Foaie de Parcurs: roadmap.md
      - Contribuții: contributing.md
  - Întrebări Frecvente: /faq
  - Cazuri de Utilizare: /use-cases
  - Blog:
    - blog/index.md
  - Reddit: /reddit
  - Discord: /discord
  - Despre:
    - Contact: contact.md
    - Politici:
      - Politica de Confidențialitate: privacy-policy.md
      - Termeni și Condiții: terms-of-service.md
      - Returnări, Rambursări și Garanție: return-refunds-warranty.md