flatten_single_child_sections: true
nav:
    - Acasă: index.md
    - Întrebări Frecvente: faq
    - Produs: product
    - Aplicație: app
    - Cazuri de Utilizare: use-cases.md
    - Recenzii: /product/minikvm/reviews/
    - Conformitate: compliance.md
    - Magazin: https://shop.techxartisan.com
    - Discord: /discord
    - Blog: blog
    - Despre: about.md