name: Deploy Redirect Site
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [trigger-build]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Deploy to GitHub Pages
        run: |
          # Create a simple site structure for GitHub Pages
          mkdir -p docs
          cp index.html docs/
          cp config.json docs/
          # Deploy to GitHub Pages
          git add docs/
          git commit -m "Deploy redirect page with config" || exit 0
          git push origin main
